site_name: HyperHTTP
site_description: A high-performance HTTP client library for Python
site_author: Latiful Mousom
repo_url: https://github.com/lmousom/hyperhttp
repo_name: lmousom/hyperhttp

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
          selection:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - User Guide:
    - Basic Usage: usage.md
    - Advanced Features: advanced.md
    - Performance Tips: performance.md
  - API Reference:
    - Client: api/client.md
    - Retry Policy: api/retry.md
    - Errors: api/errors.md
  - Development:
    - Contributing: contributing.md
    - Changelog: changelog.md 