name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel
        pip install -e ".[dev,test,doc]"

    - name: Run tests
      run: |
        pytest --cov=hyperhttp

    - name: Build package
      run: |
        python -m build

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        VERSION=${TAG#v}
        
        # Extract changes from CHANGELOG.md
        if [ -f docs/changelog.md ]; then
          echo "Found changelog file"
          CHANGES=$(awk "/## \[$VERSION\]/{flag=1;next}/## \[/{flag=0}flag" docs/changelog.md)
          echo "Extracted changes: $CHANGES"
        else
          echo "Changelog file not found"
          CHANGES="Release $VERSION"
        fi
        
        # Create GitHub release
        gh release create $TAG \
          --title "HyperHTTP $VERSION" \
          --notes "$CHANGES" \
          dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: false
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true